export const initialJobs = [
  {
    id: "vaga-1",
    title: "Professor(a) de Reforço de Matemática",
    ngo: "Instituto Saber & Futuro",
    ods: "ODS 4: Educação de Qualidade",
    odsBadge: "var(--ods-4)",
    area: "educacao",
    modality: "remoto",
    modalityLabel: "100% Remoto",
    hours: "2h/semana",
    location: "Brasil (Online)",
    skills: "Matemática, Didática, 2h/semana",
    desc: "Aulas online semanais de reforço para jovens do 9º ano da rede pública em preparação para vestibulares e cursos técnicos.",
    status: "Ativa",
  },
  {
    id: "vaga-2",
    title: "Designer Gráfico para Campanhas Sociais",
    ngo: "Coletivo Vozes da Periferia",
    ods: "ODS 17: Parcerias e Meios",
    odsBadge: "var(--ods-17)",
    area: "comunicacao",
    modality: "remoto",
    modalityLabel: "100% Remoto",
    hours: "3h/semana",
    location: "Brasil (Online)",
    skills: "Canva / Figma, Redes Sociais, 3h/semana",
    desc: "Criação de peças visuais e identidade para campanhas de arrecadação de agasalhos e cestas básicas nas redes sociais.",
    status: "Ativa",
  },
  {
    id: "vaga-3",
    title: "Instrutor de Inclusão Digital e Informática",
    ngo: "Associação Mãos Que Acolhem",
    ods: "ODS 10: Redução das Desigualdades",
    odsBadge: "var(--ods-10)",
    area: "tecnologia",
    modality: "presencial",
    modalityLabel: "Presencial",
    hours: "4h/sábado",
    location: "São Paulo - SP",
    skills: "Informática, Empatia, 4h/sábado",
    desc: "Ensino de informática básica (digitação, navegação segura, elaboração de currículos) para jovens e idosos da comunidade.",
    status: "Ativa",
  },
  {
    id: "vaga-4",
    title: "Desenvolvedor(a) Web Front-end Voluntário",
    ngo: "Rede Solidária Brasil",
    ods: "ODS 17: Parcerias e Meios",
    odsBadge: "var(--ods-17)",
    area: "tecnologia",
    modality: "remoto",
    modalityLabel: "100% Remoto",
    hours: "4h/semana",
    location: "Brasil (Online)",
    skills: "HTML / CSS, Bootstrap, 4h/semana",
    desc: "Auxílio na manutenção e aprimoramento do portal de transparência e captação de recursos da ONG com HTML, CSS e JavaScript.",
    status: "Ativa",
  },
  {
    id: "vaga-5",
    title: "Orientador(a) Pedagógico de Alfabetização",
    ngo: "Instituto Saber & Futuro",
    ods: "ODS 4: Educação de Qualidade",
    odsBadge: "var(--ods-4)",
    area: "educacao",
    modality: "hibrido",
    modalityLabel: "Híbrido",
    hours: "3h/semana",
    location: "Campinas - SP",
    skills: "Pedagogia / Letras, EJA, 3h/semana",
    desc: "Planejamento de atividades lúdicas e materiais de apoio para alfabetização de jovens e adultos (EJA).",
    status: "Ativa",
  },
  {
    id: "vaga-6",
    title: "Apoio em Triagem Social e Atendimento",
    ngo: "Associação Mãos Que Acolhem",
    ods: "ODS 10: Redução das Desigualdades",
    odsBadge: "var(--ods-10)",
    area: "social",
    modality: "presencial",
    modalityLabel: "Presencial",
    hours: "4h/semana",
    location: "São Paulo - SP",
    skills: "Serviço Social, Atendimento, 4h/semana",
    desc: "Recepção e cadastro de famílias em situação de vulnerabilidade para encaminhamento a programas de auxílio.",
    status: "Ativa",
  },
];

export const areas = {
  educacao: "Educação",
  tecnologia: "Tecnologia",
  comunicacao: "Comunicação",
  social: "Apoio social",
};
export const modalities = {
  remoto: "Remoto",
  presencial: "Presencial",
  hibrido: "Híbrido",
};
